In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns


<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [3]:
from sklearn.linear_model import LogisticRegression


In [4]:
df=pd.DataFrame({"npreg":[6,1,1,3,2,5,0,1,3,9],"glu":[148,85,89,78,197,166,118,103,126,119],"bp":[72,66,66,50,70,72,84,30,88,80],"skin":[35,29,23,32,45,19,47,38,41,35],"bmi":[33.6,26.6,28.1,31.0,30.5,25.8,45.8,43.3,39.3,29.0],"ped":[0.627,0.351,0.167,0.248,0.158,0.587,0.551,0.183,0.704,0.263],'age':[50,31,21,26,53,51,31,33,27,29],"type":[1,0,0,1,1,1,1,0,0,1]})

In [5]:
df

npreg  glu  bp  skin   bmi    ped  age  type
0      6  148  72    35  33.6  0.627   50     1
1      1   85  66    29  26.6  0.351   31     0
2      1   89  66    23  28.1  0.167   21     0
3      3   78  50    32  31.0  0.248   26     1
4      2  197  70    45  30.5  0.158   53     1
5      5  166  72    19  25.8  0.587   51     1
6      0  118  84    47  45.8  0.551   31     1
7      1  103  30    38  43.3  0.183   33     0
8      3  126  88    41  39.3  0.704   27     0
9      9  119  80    35  29.0  0.263   29     1

In [7]:
df.to_csv("E:\\data\\logistic.csv",index=False)

In [8]:
df=pd.read_csv("E:\\data\\logistic.csv")

In [11]:
from sklearn.linear_model import LogisticRegression


In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
from sklearn.model_selection import train_test_split

In [21]:
from sklearn.model_selection import train_test_split

In [24]:
x=df.iloc[:,:-1]

In [25]:
y=df.iloc[:,-1]

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state =1)

In [154]:
pridic=LogisticRegression(C=1.0)

In [155]:
pridic.fit(x_train,y_train)

E:\anakonda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [165]:
pridic.predict(x_test)

array([0, 1], dtype=int64)

In [168]:
x_test

npreg  glu  bp  skin   bmi    ped  age
2      1   89  66    23  28.1  0.167   21
9      9  119  80    35  29.0  0.263   29

In [167]:
pridic.score(x_test,y_test)

1.0

In [157]:
y_test

2    0
9    1
Name: type, dtype: int64

In [158]:
pridic.predict(x_train)

array([1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [159]:
pridic.score(x_train,y_train)

0.875

In [160]:
y_prid

array([0, 1], dtype=int64)

In [161]:
y_test

2    0
9    1
Name: type, dtype: int64

In [163]:
pridic.score(y_prid,y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[0 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [128]:
from sklearn.metrics import confusion_matrix

In [64]:
t=confusion_matrix(y_prid,y_test)

In [66]:
df

npreg  glu  bp  skin   bmi    ped  age  type
0      6  148  72    35  33.6  0.627   50     1
1      1   85  66    29  26.6  0.351   31     0
2      1   89  66    23  28.1  0.167   21     0
3      3   78  50    32  31.0  0.248   26     1
4      2  197  70    45  30.5  0.158   53     1
5      5  166  72    19  25.8  0.587   51     1
6      0  118  84    47  45.8  0.551   31     1
7      1  103  30    38  43.3  0.183   33     0
8      3  126  88    41  39.3  0.704   27     0
9      9  119  80    35  29.0  0.263   29     1

In [81]:
pridic.predict([[3,126,88,41,39.3,0.704,27]])

array([0], dtype=int64)

In [82]:
pridic.score(x_train,y_train)

0.875